djangodogs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

# this like app.use() in express
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('about/', views.About.as_view(), name = 'about'),
    path('dogs/', views.Dog_List.as_view(), name = 'dog_list'),
    # dogs
    path('dogs/new/', views.Dog_Create.as_view(), name="dog_create"),
    path('dogs/<int:pk>/', views.Dog_Detail.as_view(), name="dog_detail"),
    path('dogs/<int:pk>/update', views.Dog_Update.as_view(), name = 'dog_update'),
    path('dogs/<int:pk>delete', views.Dog_Delete.as_view(), name="dog_delete"),
    
    # profile
    path('user/<username>', views.profile, name='profile'),
   
    # dog toys
    path('dogtoys/', views.dogtoys_index, name='dogtoys_index'),
    path('dogtoys/<int:dogtoy_id>', views.dogtoys_show, name='dogtoys_show'),
    path('dogtoys/create/', views.DogToyCreate.as_view(), name='dogtoys_create'),
    path('dogtoys/<int:pk>/update/', views.DogToyUpdate.as_view(), name='dogtoys_update'),
    path('dogtoys/<int:pk>/delete/', views.DogToyDelete.as_view(), name='dogtoys_delete'),

    # auth
    path('accounts/signup/', views.signup_view, name='signup'),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class DogToy(models.Model):
    name = models.CharField(max_length=100)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name

GENDER_CHOICES = (
    ("female", "female"),
	("male", "male")
)

class Dog(models.Model):
    name = models.CharField(max_length=50)
    img = models.CharField(max_length=300)
    age = models.IntegerField()
    gender = models.CharField(max_length=10, choices = GENDER_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    dogtoys = models.ManyToManyField(DogToy)

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
    

main_app/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateView
from .models import Dog, DogToy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import DetailView
from django.urls import reverse
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class Home(TemplateView):
    template_name = 'home.html'

class About(TemplateView): 
    template_name = 'about.html'

class Dog_List(TemplateView):
    template_name = 'dog_list.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name")
        if name != None:
            context["dogs"] = Dog.objects.filter(name__icontains=name)
            context["header"] = f"Searching for {name}"
        else:
            context["dogs"] = Dog.objects.all()
            context["header"] = "All Our Dogs"
        return context

class Dog_Create(LoginRequiredMixin,CreateView):
    model = Dog
    fields = ["name", "img", "age", "gender", 'dogtoys']
    template_name = "dog_create.html"
    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect('/dogs')

class Dog_Detail(DetailView):
    model = Dog
    template_name = "dog_detail.html"

class Dog_Update(LoginRequiredMixin, UpdateView):
    model = Dog
    fields = ["name", "img", "age", "gender", 'dogtoys']
    template_name = 'dog_update.html'
    def get_success_url(self):
        return reverse('dog_detail', kwargs={'pk': self.object.pk})

class Dog_Delete(LoginRequiredMixin, DeleteView):
    model = Dog
    template_name = 'dog_delete.html'
    success_url = '/dogs/'

@login_required
def profile(request, username):
    user = User.objects.get(username=username)
    dogs = Dog.objects.filter(user=user)
    return render(request, 'profile.html', {'username': username, 'dogs': dogs})

def dogtoys_index(request):
    dogtoys = DogToy.objects.all()
    return render (request, 'dogtoy_index.html', {'dogtoys': dogtoys})

def dogtoys_show(request, dogtoy_id):
    dogtoy = DogToy.objects.get(id=dogtoy_id)
    return render(request, 'dogtoy_show.html', {'dogtoy': dogtoy})

class DogToyCreate(LoginRequiredMixin, CreateView):
    model = DogToy
    fields = '__all__'
    template_name = 'dogtoy_form.html'
    success_url='/dogtoys'

class DogToyUpdate(LoginRequiredMixin, UpdateView):
    model = DogToy
    fields = ['name', 'color']
    template_name = 'dogtoy_update.html'
    success_url='/dogtoys'

class DogToyDelete(LoginRequiredMixin, DeleteView):
    model = DogToy
    template_name='dogtoy_delete.html'
    success_url='/dogtoys'

# auth
def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if(form.is_valid()):
            user = form.save()
            login(request, user)
            print('Hello', user.username)
            return HttpResponseRedirect('/user/' + str(user.username))
        else:
            return render(request, 'signup.html', {'form': form})
    else:
        form = UserCreationForm()
        return render(request, 'signup.html', {'form': form})

main_app/templates/about.html
{% extends 'base.html' %}

{% block title%}
Abouts Page
{% endblock %}

{% block body %}
    <h1>All About Dogs</h1>
{% endblock%}

main_app/templates/dog_create.html
{% extends 'base.html' %} 
{% block body %}
	<h1>Add a Dog</h1>
	
	<form method="post">
		  {% csrf_token %} 
		  {{form.as_p}} 
		  <input type="submit" value="Submit" />
	</form>

{% endblock %}

main_app/templates/dog_delete.html
{% extends 'base.html' %} 

{% block body %}
<h1>Are you sure you want to Delete {{dog.name}}?</h1>
<form method="post">
  {% csrf_token %}
  <div>
    <input type="submit" value="Confirm" />
    <a href="{% url 'dog_detail' dog.pk %}">Cancel</a>
  </div>
</form>
{% endblock %}

main_app/templates/dog_detail.html
{% extends 'base.html' %} 

{% block body %}

<div>
  <img src="{{dog.img}}" alt="{{dog.name}}" />
</div>
    <h1>{{dog.name}}</h1>
</div>
<div>
    <h3>Age: {{dog.age}}</h3>
    <h3>Gender: {{dog.gender}}</h3>
    <h3> Toys: </h3>
    <ul class='capitalize'>
        {% for dogtoy in dog.dogtoys.all %}
            <li style='list-style: none;'>{{dogtoy.name}}</li>
        {% empty %}
            <div>Has no toys</div>
        {% endfor %}
    </ul>   
</div>
<div>
    <a class ='link' href="{% url 'dog_update' dog.pk %}">Update</a>
    <a class ='link' href="{% url 'dog_delete' dog.pk %}">Delete</a>
</div>

{% endblock %}

main_app/templates/dog_list.html
{% extends 'base.html' %}

{% block title %}
    Dog List
{% endblock %}

{% block body %}
    <form>
        <div>
            <input type="text" name="name" placeholder="Name of dog"/>
            <input type="submit" value="Search"/>
        </div>
    </form>
    <h1>{{header}}</h1>
    {% for dog in dogs %}
        <img src="{{dog.img}}" alt="{{dog.name}}">
        <a class='dogName' href="{% url 'dog_detail' dog.pk %}">
            <h3>Name: {{dog.name}}</h3>
        </a>
        <h3>Age: {{dog.age}}</h3>
        <h3>Gender: {{dog.gender}}</h3>
        <p>Adopted By: 
            <a class='userName' href='/user/{{dog.user.username}}'>{{dog.user.username}}</a>
        </p>
    {% endfor %}
{% endblock %}

main_app/templates/dog_update.html
{% extends 'base.html' %} 

{% block body %}
<h1>Update {{dog.name}}</h1>

<form action="" method="post">
  {% csrf_token %} 
  {{form.as_p}} 
  <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/dogtoy_delete.html
{% extends 'base.html' %}

{% block body %}
    <h1>Delete Dog Toy</h1>

    <h4>Are you sure you want to DELETE {{ dogtoy }}?</h4>

    <form action="" method="POST">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a class='link' href="{% url 'dogtoys_show' dogtoy.id %}">Cancel</a>
    </form>
{% endblock %}

main_app/templates/dogtoy_form.html
{% extends 'base.html' %} 

{% block body %}
    <h1>Add a Dog Toy</h1>

    <form action="" method="post">
    {% csrf_token %} 
        {{form.as_p}} 
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

main_app/templates/dogtoy_index.html
{% extends 'base.html' %}
{% block body %}

<h1>List of Dog Toys</h1>

{% for dogtoy in dogtoys %}
    <div>
        <a class='link' href="{% url 'dogtoys_show' dogtoy.id %}">
            <div>
                <h3 class='capitalize'>{{ dogtoy.name }}</h3>
            </div>
        </a>
    </div>
{% endfor %}

{% endblock %}

main_app/templates/dogtoy_show.html
{% extends 'base.html' %}
{% block body %}

<h1>Dog Toy Details</h1>

<div>
    <div>
        <span class='capitalize'>{{ dogtoy.name }}</span>
        <p>Color: {{ dogtoy.color }}</p>
        {% for dog in dogtoy.dog_set.all %}
        <p>Owned by: {{dog.name}}</p>
        {% empty %}
            <p>Nobody plays with this toy</p>
        {% endfor %}
    </div>
    <div>
        <a class ='link' href="{% url 'dogtoys_update' dogtoy.id %}">Edit</a>
        <a class ='link' href="{% url 'dogtoys_delete' dogtoy.id %}">Delete</a>
    </div>
</div>
{% endblock %}

main_app/templates/dogtoy_update.html
{% block body %}
<h1>Update {{dogtoy.name}}</h1>

<form action="" method="post">
  {% csrf_token %} 
  {{form.as_p}} 
  <input type="submit" value="Submit" />
</form>

{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}

{% block title %}
    All the Dogs
{% endblock %}

{% block body %}
    <h1>Who Let The Dogs Out</h1>
    <img class = "mainPic" src="https://i.pinimg.com/736x/b6/e0/3b/b6e03bb3c8ad5c8fe3c5b0cc1f5d2f1e.jpg"/>

{% endblock%}

main_app/templates/profile.html
{% extends 'base.html' %}
{% block body %}

<h1 class='capitalize'>{{ username }}'s Dogs:</h1>

{% for dog in dogs %}
<a class ='link' href="/dogs/{{ dog.id }}">
  <h3>{{ dog.name }}</h3>
</a>

{% endfor %}

{% endblock %}

main_app/templates/signup.html
{% extends 'base.html' %}

{% block body %}
  <h2>Sign up</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}